//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemChecker.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class TryskinsConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static TryskinsConfig defaultInstance = ((TryskinsConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TryskinsConfig())));
        
        public static TryskinsConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int maxTryskinsPrecent {
            get {
                return ((int)(this["maxTryskinsPrecent"]));
            }
            set {
                this["maxTryskinsPrecent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int minTryskinsPrecent {
            get {
                return ((int)(this["minTryskinsPrecent"]));
            }
            set {
                this["minTryskinsPrecent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxTryskinsPrice {
            get {
                return ((int)(this["maxTryskinsPrice"]));
            }
            set {
                this["maxTryskinsPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minTryskinsPrice {
            get {
                return ((int)(this["minTryskinsPrice"]));
            }
            set {
                this["minTryskinsPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int minPrecentW {
            get {
                return ((int)(this["minPrecentW"]));
            }
            set {
                this["minPrecentW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int maxPrecentW {
            get {
                return ((int)(this["maxPrecentW"]));
            }
            set {
                this["maxPrecentW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int minSalesW {
            get {
                return ((int)(this["minSalesW"]));
            }
            set {
                this["minSalesW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool souvenirW {
            get {
                return ((bool)(this["souvenirW"]));
            }
            set {
                this["souvenirW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stickerW {
            get {
                return ((bool)(this["stickerW"]));
            }
            set {
                this["stickerW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool fastTime {
            get {
                return ((bool)(this["fastTime"]));
            }
            set {
                this["fastTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool longTime {
            get {
                return ((bool)(this["longTime"]));
            }
            set {
                this["longTime"] = value;
            }
        }
    }
}
