//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemChecker.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class TryskinsConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static TryskinsConfig defaultInstance = ((TryskinsConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TryskinsConfig())));
        
        public static TryskinsConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int maxTryskinsPrecent {
            get {
                return ((int)(this["maxTryskinsPrecent"]));
            }
            set {
                this["maxTryskinsPrecent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int minTryskinsPrecent {
            get {
                return ((int)(this["minTryskinsPrecent"]));
            }
            set {
                this["minTryskinsPrecent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maxTryskinsPrice {
            get {
                return ((int)(this["maxTryskinsPrice"]));
            }
            set {
                this["maxTryskinsPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minTryskinsPrice {
            get {
                return ((int)(this["minTryskinsPrice"]));
            }
            set {
                this["minTryskinsPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sales {
            get {
                return ((int)(this["sales"]));
            }
            set {
                this["sales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool compareSt {
            get {
                return ((bool)(this["compareSt"]));
            }
            set {
                this["compareSt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dontUpload {
            get {
                return ((bool)(this["dontUpload"]));
            }
            set {
                this["dontUpload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int loadData {
            get {
                return ((int)(this["loadData"]));
            }
            set {
                this["loadData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool oldDesign {
            get {
                return ((bool)(this["oldDesign"]));
            }
            set {
                this["oldDesign"] = value;
            }
        }
    }
}
